spring:
  application:
    name: auth-server
  ds-authserver:
    url: jdbc:mysql://localhost:3306/authserver
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  ds-oauth:
    url: jdbc:mysql://localhost:3306/authserver_oauth
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
#        hbm2ddl:
#          auto: validate
  h2:
    console:
      enabled: true

server:
  port: 9999

#eureka:
#  client:
#    region: default
#    registryFetchIntervalSeconds: 5
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/


logging.level:
  org.springframework: WARN
  org.springframework.web: DEBUG
  org.springframework.security: DEBUG

security:
  oauth2:
    resource:
      filter-order: 3

jwt:
  signing-key: ipg3d4at5bW1zJ4i0UW8X8W59d51EiOE5Sa8X8o4ZKCCp0MU88KfalEEDfQfZHb
  expiration-time: 60000

endpoints.default.web.enabled: true